name: Deploy ASP.NET to Azure

on:
  push:
    branches:
      - master  # or 'main' depending on your default branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore "01.First Step.sln"

      - name: Install CodeDom Provider (required for build)
        run: nuget install Microsoft.CodeDom.Providers.DotNetCompilerPlatform -Version 2.0.1

      - name: Build the solution
        run: msbuild "01.First Step.sln" /p:Configuration=Release

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: atkfirstweb   # 🟢 আপনার Azure App Service নাম
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/01.First Step/bin/Release
