name: Deploy ASP.NET Web Site to Azure

on:
  push:
    branches:
      - master  # অথবা main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework environment
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Create zip package manually
        run: |
          mkdir publish
          powershell Compress-Archive -Path "01.First Step\*" -DestinationPath publish\app.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: atkfirstweb  # <-- আপনার Azure App Service এর নাম
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish/app.zip
